# Site settings
title: Sawyer Valin
email: officialsawyervalin@gmail.com
description: Creative Technologist & Data Explorer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username: sawyervalin

# Build settings
markdown: kramdown
